Author: Carlos Roberto de Melo

Date: 06/18/2020
    
Obj: Convert the quantities of MGE output into physical quantities that can be used for the dynamic model (JAM).

In [1]:
import numpy as np

In [2]:
#Some properties of img
#Imagem SDP.81 WFC3/HST

SCALE = 0.09                 #arcsec
EXPTIME = 4417.621094        #seconds
AB_zeropoint = 25.936      #Vega magnitude zeropoint in the F160w band from (https://www.stsci.edu/hst/instrumentation/wfc3/data-analysis/photometric-calibration/ir-photometric-calibration)
M_AB = 4.60             #Magnitude absoluta do Sol com relação a Vega, na banda ACS/F814W from Willmer, Christopher N. A. (2018)

In [3]:
#Lendo a saída do MGE
TotalCounts, SigmaPixel, qObs = np.loadtxt('MGE_Output_without_arcs.txt', unpack=True)
TotalCounts = TotalCounts*EXPTIME
TotalCounts/TotalCounts[0]

array([1.        , 2.00458658, 1.67272341, 3.49909647, 1.57139447,
       3.92411154, 3.89484221, 7.43209639])

In [4]:
#Agora vamos converter o total de contagens no pico de brilho superfícial C_0
C_0 = TotalCounts/(2*np.pi*(SigmaPixel**2)*qObs) #Via equation (1) Cappellari (2002)
C_0

array([498851.78828564, 154392.0017574 ,  22269.54095846,   7261.54799362,
         4587.33545143,   1880.70170698,   1488.979313  ,    643.60412486])

In [5]:
C_0

array([498851.78828564, 154392.0017574 ,  22269.54095846,   7261.54799362,
         4587.33545143,   1880.70170698,   1488.979313  ,    643.60412486])

In [6]:
SigmaPixel*SCALE

array([0.04569021, 0.13002768, 0.2552859 , 0.58830138, 0.66883275,
       1.22418549, 1.76055489, 3.25551357])

In [7]:
#Agora calculamos o brilho superfícial na banda F160w usando Vega como referência
#Pelo https://www.stsci.edu/itt/review/dhb_2011/WFC3/wfc3_Ch73.html, a relação entre contagens e magnitue é 
                #WFC3MAG = -2.5log (count rate [e− s-1])
#Além disso, a relação entre Surface brightnesses e total magnitude é
                # S = m + 2.5 log(Área)
#em que S é a Surface brightnesses, m a magnitude e Área = Scale² =. Deste modo, obtemos para cada gaussiana do MGE:

S = (-2.5*np.log10(C_0) + 2.5*np.log10(EXPTIME) + 5*np.log10(SCALE) + AB_zeropoint +0.1)
        

In [8]:
m = S - 5*np.log10(SCALE)
m

array([20.90404232, 22.17740916, 24.279693  , 25.49639813, 25.99506991,
       26.96317136, 27.2167495 , 28.12742411])

In [9]:
## ABMAG
aux = 10**(-0.4*m)
mf = -2.5*np.log10(aux.sum())
mf

20.549686194354393

Referencias:
    

    Vega Zero Point (https://www.stsci.edu/hst/instrumentation/wfc3/data-analysis/photometric-calibration/ir-photometric-calibration)
    Willmer, Christopher N. A. (2018) (https://iopscience.iop.org/article/10.3847/1538-4365/aabfdf)
    WFC3 MAG (https://www.stsci.edu/itt/review/dhb_2011/WFC3/wfc3_Ch73.html)